auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9095
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
  chunk_idle_period: 15m
  max_transfer_retries: 0
schema_config:
  configs:
    - from: 2020-10-13
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
frontend_worker:
  frontend_address: 127.0.0.1
  ring:
    kvstore:
      store: inmemory
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
chunk_store_config:
  max_look_back_period: 0s
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
  clean_sharded_index_period: 10m
  index_queries_cache_config:
    max_size: 25000
    max_age: 24h
  chunk_queries_cache_config:
    max_size: 25000
    max_age: 24h