version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    links:
      - prometheus

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    volumes:
      - ./loki:/etc/loki
    depends_on:
      - grafana

  random-logger:
    image: alpine
    command: sh -c "while true; do echo 'random_metric $(($RANDOM % 100))'; sleep 1; done"
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: httpd.access

  fluentd:
    build: .
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"